Repository msazurestackworkloads/kubetools, pull requests merged in 2019-04, with the labels that each got.

#3 Moving wordpress code from different repo to one place.
  application/wordpress/cleanup.sh
  application/wordpress/deployment.sh
  applications/wordpress/cleanup.sh
  applications/wordpress/deploy.sh
  applications/wordpress/install_wordpress_on_kubernete_in_helm_test.sh
  applications/wordpress/validate.sh
  config/testmatrix_staging.json
Labels: enhancement

#4 Adding the missing file and renaming the file name.
  applications/wordpress/deploy.sh
  applications/wordpress/install_helm.sh
  applications/wordpress/install_wordpress_using_helm.sh
Labels: enhancement

#5 Schema changes for Test validation
  applications/wordpress/cleanup.sh
  applications/wordpress/deploy.sh
  applications/wordpress/validate.sh
  config/testmatrix_staging.json
Labels: enhancement

#8 Adding number of Azure Stack node configuration.
  config/aksEngineK8s_testsuite_staging.json
  config/aksEngine_sqlaris_staging.json
Labels: enhancement

#9 Filename change.
  config/aksEngineK8s_sqlaris_staging.json
Labels: bug

#21 Fixing some cases for SQLAris and logging more.
  applications/sqlaris/deploy_test.sh
  applications/sqlaris/run_clean.sh
  applications/sqlaris/run_deploy.sh
  applications/sqlaris/run_parse.sh
Labels: bug

#25 Cleanup code from master VM.
  applications/sonobuoy/cleanup.sh
  applications/sonobuoy/deploy.sh
  applications/sonobuoy/validate.sh
  applications/wordpress/cleanup.sh
  applications/wordpress/deploy.sh
Labels: bug

#26 Move back sonobuoy runs to full.
  applications/sonobuoy/deploy.sh
  applications/sonobuoy/validate.sh
Labels: bug

#28 Bug fixes
  applications/sonobuoy/validate.sh
  applications/wordpress/cleanup.sh
  applications/wordpress/deploy.sh
  applications/wordpress/install_wordpress_using_helm.sh
Labels: bug

#29 Adding more retry to log collection logic.
  applications/sonobuoy/validate.sh
  applications/wordpress/install_helm.sh
Labels: bug

#31 Adding XML file name to use to calculate test cases.
  config/aksEngineK8s_testsuite_staging.json
Labels: enhancement

#35 added result file configuration changes
  config/aksEngineK8s_sqlaris_staging.json
Labels: enhancement

#36 Tomcat stateless app addition
  applications/common/common.sh
  applications/common/install_helm.sh
  applications/tomcat/cleanup.sh
  applications/tomcat/deploy.sh
  applications/tomcat/validate.sh
  applications/wordpress/deploy.sh
Labels: enhancement

#37 removed junit result setting
  config/aksEngineK8s_testsuite_staging.json
Labels: bug

#39 Move to new aks-engine binary
  config/aksEngineK8s_sqlaris_staging.json
  config/aksEngineK8s_testsuite_staging.json
Labels: enhancement

#40 Moving result XML file and removing one master deployment matrix.
  config/aksEngineK8s_testsuite_staging.json
Labels: enhancement

#41 Adding stateless app tomcat and timeout in sonobuoy validation code.
  applications/sonobuoy/validate.sh
  config/aksEngineK8s_testsuite_staging.json
Labels: bug, enhancement

#44 Tomcat to point to correct branch.
  applications/tomcat/deploy.sh
Labels: bug

#46 Moving the files to respective folders.
  config/master/aksEngineK8s_containerApps_master.json
  config/staging/aksEngineK8s_Akstest_staging.json
  config/staging/aksEngineK8s_containerApps_staging.json
  config/staging/aksEngineK8s_sqlaris_staging.json
Labels: enhancement
